---
- hosts: localhost
  become: yes
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - role: initial-setup
      tags: setup

    - role: docker-compose
      tags: compose
